## Application name.
spring.application.name: gateway-server

## Server HTTP port.
server.port: 8080

## active profile (get from maven build --> check pom.xml)
spring.profiles.active: "local"
  
## Zull config
zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: ${gateway.timeout}
    socket-timeout-millis: ${gateway.timeout}
  routes:
    server-auth:
      path: /uaa/**
      stripPrefix: false
      sensitiveHeaders: 
      
    user-service:
      path: /user/**
      stripPrefix: true
      sensitiveHeaders:
 
## Enabel Admin server security
management.security.enabled: false

## Timeout for the gateway
gateway.timeout: 5000

## Eureka sever param
eureka:
  server:
    host: localhost
    port: 8761
    security:
      name: discovery
      password: discovery123
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5    
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${DISCOVERY_URI:http://${eureka.server.security.name}:${eureka.server.security.password}@${eureka.server.host}:${eureka.server.port}/eureka}
     
feign:
  client:
    config:
      default:
        connectTimeout:  ${gateway.timeout}
        readTimeout:  ${gateway.timeout}

ribbon:
  ReadTimeout: ${gateway.timeout}
  ConnectTimeout: ${gateway.timeout}
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 2
